name: Java CI + Docker

on:
  push:
    branches:
      - main
      - test-branch-CI
  pull_request:
    branches:
      - main
      - test-branch-CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build com Maven e teste
      run: mvn clean install 

    - name: Build Docker image
      run: docker build -t meuapp:latest .
